//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlarmDto", Namespace="http://schemas.datacontract.org/2004/07/SCADA_Core.DTOs")]
    public partial class AlarmDto : object
    {
        
        private bool AcknowledgedField;
        
        private string AlarmNameField;
        
        private double LimitField;
        
        private ServiceReference1.AlarmPriority PriorityField;
        
        private string TagIdField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Acknowledged
        {
            get
            {
                return this.AcknowledgedField;
            }
            set
            {
                this.AcknowledgedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlarmName
        {
            get
            {
                return this.AlarmNameField;
            }
            set
            {
                this.AlarmNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Limit
        {
            get
            {
                return this.LimitField;
            }
            set
            {
                this.LimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.AlarmPriority Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagId
        {
            get
            {
                return this.TagIdField;
            }
            set
            {
                this.TagIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlarmPriority", Namespace="http://schemas.datacontract.org/2004/07/SCADA_Core.Enums")]
    public enum AlarmPriority : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Medium = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TriggeredAlarmDto", Namespace="http://schemas.datacontract.org/2004/07/SCADA_Core.DTOs")]
    public partial class TriggeredAlarmDto : object
    {
        
        private ServiceReference1.Alarm AlarmField;
        
        private string TagDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Alarm Alarm
        {
            get
            {
                return this.AlarmField;
            }
            set
            {
                this.AlarmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagDescription
        {
            get
            {
                return this.TagDescriptionField;
            }
            set
            {
                this.TagDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alarm", Namespace="http://schemas.datacontract.org/2004/07/SCADA_Core.Models")]
    public partial class Alarm : object
    {
        
        private bool AcknowledgedField;
        
        private string AlarmNameField;
        
        private string IdField;
        
        private double LimitField;
        
        private ServiceReference1.AlarmPriority PriorityField;
        
        private string TagIdField;
        
        private System.DateTime TimeField;
        
        private ServiceReference1.AlarmType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Acknowledged
        {
            get
            {
                return this.AcknowledgedField;
            }
            set
            {
                this.AcknowledgedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlarmName
        {
            get
            {
                return this.AlarmNameField;
            }
            set
            {
                this.AlarmNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Limit
        {
            get
            {
                return this.LimitField;
            }
            set
            {
                this.LimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.AlarmPriority Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagId
        {
            get
            {
                return this.TagIdField;
            }
            set
            {
                this.TagIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.AlarmType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlarmType", Namespace="http://schemas.datacontract.org/2004/07/SCADA_Core.Enums")]
    public enum AlarmType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Above = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Below = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAlarmController", CallbackContract=typeof(ServiceReference1.IAlarmControllerCallback))]
    public interface IAlarmController
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmController/GetAll", ReplyAction="http://tempuri.org/IAlarmController/GetAllResponse")]
        ServiceReference1.AlarmDto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmController/GetAll", ReplyAction="http://tempuri.org/IAlarmController/GetAllResponse")]
        System.Threading.Tasks.Task<ServiceReference1.AlarmDto[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmController/Subscribe", ReplyAction="http://tempuri.org/IAlarmController/SubscribeResponse")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmController/Subscribe", ReplyAction="http://tempuri.org/IAlarmController/SubscribeResponse")]
        System.Threading.Tasks.Task SubscribeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IAlarmControllerCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAlarmController/OnAlarmTriggered")]
        void OnAlarmTriggered(ServiceReference1.TriggeredAlarmDto triggeredAlarmDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IAlarmControllerChannel : ServiceReference1.IAlarmController, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class AlarmControllerClientBase : System.ServiceModel.DuplexClientBase<ServiceReference1.IAlarmController>, ServiceReference1.IAlarmController
    {
        
        public AlarmControllerClientBase(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public ServiceReference1.AlarmDto[] GetAll()
        {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AlarmDto[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public void Subscribe()
        {
            base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task SubscribeAsync()
        {
            return base.Channel.SubscribeAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    public class OnAlarmTriggeredReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public OnAlarmTriggeredReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference1.TriggeredAlarmDto triggeredAlarmDto
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference1.TriggeredAlarmDto)(this.results[0]));
            }
        }
    }
    
    public partial class AlarmControllerClient : AlarmControllerClientBase
    {
        
        public AlarmControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                this(new AlarmControllerClientCallback(), binding, remoteAddress)
        {
        }
        
        private AlarmControllerClient(AlarmControllerClientCallback callbackImpl, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), binding, remoteAddress)
        {
            callbackImpl.Initialize(this);
        }
        
        public event System.EventHandler<OnAlarmTriggeredReceivedEventArgs> OnAlarmTriggeredReceived;
        
        private void OnOnAlarmTriggeredReceived(object state)
        {
            if ((this.OnAlarmTriggeredReceived != null))
            {
                object[] results = ((object[])(state));
                this.OnAlarmTriggeredReceived(this, new OnAlarmTriggeredReceivedEventArgs(results, null, false, null));
            }
        }
        
        private class AlarmControllerClientCallback : object, IAlarmControllerCallback
        {
            
            private AlarmControllerClient proxy;
            
            public void Initialize(AlarmControllerClient proxy)
            {
                this.proxy = proxy;
            }
            
            public void OnAlarmTriggered(ServiceReference1.TriggeredAlarmDto triggeredAlarmDto)
            {
                this.proxy.OnOnAlarmTriggeredReceived(new object[] {
                            triggeredAlarmDto});
            }
        }
    }
}
